<!-- Navigation -->
<div id="navigation"> 
		<ul id="navlist">
			<li><a href="index.php">Home</a></li>
			<li><a href="index.php?p=login">Log in</a></li>
			<li><a href="index.php?p=contact">Contact</a></li>
			<!--use php to make the following dynamic -->
			<li><p><strong>A tiny little service announcement.</strong><br/>Put all your little tidbits of information or pictures or dynamic widgets in this area </p></li>
		</ul>
</div>
<!-- Navigation -->